### ISSUE TITLE
Please move existing (and defunct) site from Codehaus to Github pages.

### ISSUE THREAD

**Issue by mykelalvis** [sonatype/modello#21]
Codehaus has shut its doors, which I'm sure everyone knows.  

Best urrent access I could find is via http://web.archive.org/web/20150506134053/http://modello.codehaus.org/

Please move existing docs into Wiki or github's gh-pages

**Comment by rfscholte** [comment]
documentaton available at http://codehaus-plexus.github.io/modello/
